apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-continuity-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: activemq-artemis-continuity-operator
  template:
    metadata:
      labels:
        name: activemq-artemis-continuity-operator
    spec:
      serviceAccountName: activemq-artemis-continuity-operator
      containers:
        - name: activemq-artemis-continuity-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - activemq-artemis-continuity-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "activemq-artemis-continuity-operator"
