// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v2alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuity":       schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuity(ref),
		"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuitySpec":   schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuitySpec(ref),
		"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuityStatus": schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuityStatus(ref),
	}
}

func schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisContinuity is the Schema for the activemqartemiscontinuities API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuitySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuityStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuitySpec", "github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuityStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuitySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisContinuitySpec defines the desired state of ActiveMQArtemisContinuity",
				Properties: map[string]spec.Schema{
					"adminUser": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"adminPassword": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"deploymentPlan": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.DeploymentPlanType"),
						},
					},
					"acceptors": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.AcceptorType"),
									},
								},
							},
						},
					},
					"connectors": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ConnectorType"),
									},
								},
							},
						},
					},
					"console": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ConsoleType"),
						},
					},
					"siteId": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"localContinuityUser": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"localContinuityPass": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"peerSiteUrl": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"peerContinuityUser": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"peerContinuityPass": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"servingAcceptors": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"activeOnStart": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"brokerIdCacheSize": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"inflowStagingDelay": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"bridgeInterval": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"bridgeIntervalMultiplier": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"number"},
							Format: "float",
						},
					},
					"inflowAcksConsumedPollDuration": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"activationTimeout": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"reorgManagement": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"continuityLogLevel": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"siteId", "localContinuityUser", "localContinuityPass", "peerSiteUrl", "peerContinuityUser", "peerContinuityPass", "servingAcceptors", "activeOnStart"},
			},
		},
		Dependencies: []string{
			"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.AcceptorType", "github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ConnectorType", "github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ConsoleType", "github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.DeploymentPlanType"},
	}
}

func schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuityStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisContinuityStatus defines the observed state of ActiveMQArtemisContinuity",
				Properties: map[string]spec.Schema{
					"podStatus": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Ref:         ref("github.com/RHsyseng/operator-utils/pkg/olm.DeploymentStatus"),
						},
					},
				},
				Required: []string{"podStatus"},
			},
		},
		Dependencies: []string{
			"github.com/RHsyseng/operator-utils/pkg/olm.DeploymentStatus"},
	}
}
