// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v2alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuity":       schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuity(ref),
		"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuitySpec":   schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuitySpec(ref),
		"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuityStatus": schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuityStatus(ref),
	}
}

func schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisContinuity is the Schema for the activemqartemiscontinuities API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuitySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuityStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuitySpec", "github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ActiveMQArtemisContinuityStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuitySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisContinuitySpec defines the desired state of ActiveMQArtemisContinuity",
				Properties: map[string]spec.Schema{
					"adminUser": {
						SchemaProps: spec.SchemaProps{
							Description: "User name for standard broker user. It is required for connecting to the broker. If left empty, it will be generated.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"adminPassword": {
						SchemaProps: spec.SchemaProps{
							Description: "Password for standard broker user. It is required for connecting to the broker. If left empty, it will be generated.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"deploymentPlan": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.DeploymentPlanType"),
						},
					},
					"acceptors": {
						SchemaProps: spec.SchemaProps{
							Description: "Configuration of all acceptors",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.AcceptorType"),
									},
								},
							},
						},
					},
					"connectors": {
						SchemaProps: spec.SchemaProps{
							Description: "Configuration of all connectors",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ConnectorType"),
									},
								},
							},
						},
					},
					"console": {
						SchemaProps: spec.SchemaProps{
							Description: "Configuration for the embedded web console",
							Ref:         ref("github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ConsoleType"),
						},
					},
					"siteId": {
						SchemaProps: spec.SchemaProps{
							Description: "Name the continuity site. Must be unique in the set of peers (is same across the artemis cluster)",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"localContinuityUser": {
						SchemaProps: spec.SchemaProps{
							Description: "Username to connect to the local broker for continuity connections.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"localContinuityPass": {
						SchemaProps: spec.SchemaProps{
							Description: "Password to connect to the local broker for continuity connections.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"peerSiteUrl": {
						SchemaProps: spec.SchemaProps{
							Description: "Username to connect to the peer site broker/cluster for continuity connections.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"peerContinuityUser": {
						SchemaProps: spec.SchemaProps{
							Description: "Username to connect to the peer site broker/cluster for continuity connections.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"peerContinuityPass": {
						SchemaProps: spec.SchemaProps{
							Description: "Password to connect to the peer site broker/cluster for continuity connections.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"servingAcceptors": {
						SchemaProps: spec.SchemaProps{
							Description: "List of acceptors that used for serving external clients. Continuity will control these acceptors to prevent producers and consumer from interacting while the site isn't active.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"activeOnStart": {
						SchemaProps: spec.SchemaProps{
							Description: "Identifies this site should be active when first started. If another active site is connected to, this site will defer to the other. You can also start both sites inactive and explictly activate the desired start.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"brokerIdCacheSize": {
						SchemaProps: spec.SchemaProps{
							Description: "Size of the broker id cache size, used by the broker to remove duplicate messages across sites. Make sure the id cache is sufficiently sized for your volume of messages. The default is 3000.",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"inflowStagingDelay": {
						SchemaProps: spec.SchemaProps{
							Description: "Amount of time in millseconds to delay messages in the inflow staging queues before delivering them to the target queues. Useful for active:active site topologies. The default is 60000 ms or 1 minute.",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"bridgeInterval": {
						SchemaProps: spec.SchemaProps{
							Description: "Bridge reconnection interval for all the bridges created by the continuity plugin. The default is 1000 ms or 1 second.",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"bridgeIntervalMultiplier": {
						SchemaProps: spec.SchemaProps{
							Description: "Bridge reconnection interval backoff multiplier for all the bridges created by the continuity plugin. The default is 0.5.",
							Type:        []string{"number"},
							Format:      "float",
						},
					},
					"outflowExhaustedPollDuration": {
						SchemaProps: spec.SchemaProps{
							Description: "Time in milliseconds between polls to check for a site to be exhausted during deactivation. The default is 100 ms.",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"inflowAcksConsumedPollDuration": {
						SchemaProps: spec.SchemaProps{
							Description: "Time in milliseconds between polls to all the inflow acks have been consumed during activation. The default is 100 ms.",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"activationTimeout": {
						SchemaProps: spec.SchemaProps{
							Description: "Time in milliseconds to activate a site and start serving clients, overriding the wait for the peer site to be exhausted, and acks to be consumed. The default is 300000 ms or 5 minutes.",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"reorgManagement": {
						SchemaProps: spec.SchemaProps{
							Description: "Whether or not to reorganized all the address, queue, divert, and bridge primitives under the continuity hierarchy in JMX/Jolokia. The default is true.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"continuityLogLevel": {
						SchemaProps: spec.SchemaProps{
							Description: "Logging level for the continuity plugin (TRACE, DEBUG, INFO, or ERROR). The default is INFO.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"siteId", "localContinuityUser", "localContinuityPass", "peerSiteUrl", "peerContinuityUser", "peerContinuityPass", "servingAcceptors", "activeOnStart"},
			},
		},
		Dependencies: []string{
			"github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.AcceptorType", "github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ConnectorType", "github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.ConsoleType", "github.com/rh-messaging/activemq-artemis-continuity-operator/pkg/apis/broker/v2alpha1.DeploymentPlanType"},
	}
}

func schema_pkg_apis_broker_v2alpha1_ActiveMQArtemisContinuityStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisContinuityStatus defines the observed state of ActiveMQArtemisContinuity",
				Properties: map[string]spec.Schema{
					"podStatus": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/RHsyseng/operator-utils/pkg/olm.DeploymentStatus"),
						},
					},
				},
				Required: []string{"podStatus"},
			},
		},
		Dependencies: []string{
			"github.com/RHsyseng/operator-utils/pkg/olm.DeploymentStatus"},
	}
}
